language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO="django==1.7.10"
  - DJANGO="django==1.8.7"

install:
  - pip install $DJANGO
  - pip install celery==3.1.16
  - pip install django-enumfield==1.2
  - pip install django-extensions==1.5.1
  - pip install django-model-utils==2.4
  - pip install shortuuid==0.4.2
  - pip install coveralls mock factory_boy

script:
  - coverage run --source=ticker runtests.py

after_success:
  coveralls

notifications:
  email:
    recipients:
      - zach.smith@makespace.com
    on_success: change
    on_failure: change
