name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  tests:
    name: Python ${{ matrix.python-version }} / Django ${{ matrix.django-version }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version:
        - "2.7"
        - "3.4"
        - "3.5"
        django-version:
        - "1.8.7"
        - "1.9"
        - "1.10"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade tox tox-py
        python -m pip install django==${{ matrix.django-version }}
        python -m pip install celery==3.1.16
        python -m pip install django-light-enums==0.1.2
        python -m pip install django-extensions==1.5.1
        python -m pip install django-model-utils==2.4
        python -m pip install shortuuid==0.4.2
        python -m pip install coveralls mock factory_boy
        python -m pip install freezegun==0.3.4

    - name: Run tests
      run: coverage run --source=umeboshi setup.py test
